export type FeedbackRow = { text: string; cat: 'good' | 'keyword' | 'bad'; date: string; product: string; who: string; duration: string; effect: string; issue: string; attachment: string }
export const DD_FEEDBACK: FeedbackRow[] = [
{
"text": "己经喝了一个星期了,味道不错,有山渣的味道",
"cat": "good",
"date": "",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "IMG_0603.JPEG"
},
{
"text": "But I think the itchyness on my skin abit better",
"cat": "good",
"date": "25/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "1个星期",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "IMG_0436.JPEG"
},
{
"text": "真的很好，一瓶还没喝完皮肤好了",
"cat": "good",
"date": "08/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "1瓶",
"effect": "",
"issue": "",
"attachment": "IMG_9684.JPEG"
},
{
"text": "疫情打了疫苗后 一直痒",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "股藓",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "红班狼瘡者",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "货收到了 全部ok",
"cat": "good",
"date": "05/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "IMG_9003.JPEG"
},
{
"text": "上次货物到时,没有很安全的包装\n上次送货,里面的包装有破损,幸好里面瓶装没有破裂,谢谢你通知包装公司,安全包装🙏🙏🙏",
"cat": "good",
"date": "23/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "sg 送货.png"
},
{
"text": "好像是荨麻疹  偶尔阶段性就会红红一片！全是一小粒  好了又在另外的地方来",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "脚麻后遗症 不痛不痒",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "身体痒，发出粒粒",
"cat": "keyword",
"date": "",
"product": "DD",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "血管爆",
"cat": "keyword",
"date": "08/02/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "因为电疗后的后遗症 引起眼睛干涩、有时模糊",
"cat": "keyword",
"date": "09/02/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "After 白内障cataract surgeries on both eyes over 14 months, have discharge frequently blocking sight. So have to use eye drops very often.",
"cat": "keyword",
"date": "09/02/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "I still have stock which I recently bought during promotions at pharmacy where by I been taking for many years which I found it very useful.",
"cat": "good",
"date": "09/02/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "关节比較好点",
"cat": "good",
"date": "10/02/2026",
"product": "KHH",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "风湿，以前啊 早上早早5-6点 割树胶啊 还有在工厂做工 一直站着啊 伤到那个神经线这样咯 搬一箱箱的东西啊",
"cat": "keyword",
"date": "12/02/2026",
"product": "KHH",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "味道👍眼睛看东西有清亮点还可以👍",
"cat": "good",
"date": "24/02/2026",
"product": "NE",
"who": "celynn",
"duration": "1个礼拜了",
"effect": "眼睛清楚",
"issue": "",
"attachment": "Screenshot 2026-02-24 at 11.18.13 AM.png"
},
{
"text": "老板下午好我喝到第四盒的肘候我的飞蚊症\n蚊症蚯蚓 不见了 谢谢老板你们的产品",
"cat": "good",
"date": "24/02/2026",
"product": "NE",
"who": "celynn",
"duration": "4盒",
"effect": "飞蚊症",
"issue": "",
"attachment": "Screenshot 2026-01-30 at 3.14.04 PM.png"
},
{
"text": "眼晴在看了一/二小时的手机荧幕 或书本文字后  就会出现眼袋那范围一片鳥黑",
"cat": "keyword",
"date": "24/02/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "喝了一个星期眼睛比较亮",
"cat": "good",
"date": "23/02/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-02-24 115113.png"
},
{
"text": "眼睛没那么容易干了",
"cat": "good",
"date": "16/02/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-02-24 115228.png"
},
{
"text": "重影，酸涨痛，眼压，怕光",
"cat": "keyword",
"date": "22/02/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "视网膜脱落",
"cat": "keyword",
"date": "26/02/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "头发很幼",
"cat": "keyword",
"date": "27/02/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "喝了3/4天还不错，感觉皮肤有变好，有好睡",
"cat": "good",
"date": "01/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "今早我喝了25ml，有感觉今天头皮都没有这样痒了",
"cat": "good",
"date": "01/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": ""
},
{
"text": "黄斑病看东西没有斜歪了",
"cat": "good",
"date": "02/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "黄斑病变",
"issue": "",
"attachment": "屏幕截图 2026-03-02 105346.png"
},
{
"text": "眼睛不干了",
"cat": "good",
"date": "02/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-03-02 105415.png"
},
{
"text": "01111291543\n字眼：干眼，流眼泪，因为吹冷气\n每天带狗散步晒太阳\n在太阳底下做工修车\n在太阳底下种花\n以前年轻不照顾\n青光眼是突然间的\n\n好评：上个月验眼睛，眼压没有问题了\n之前飞蚊症有5-6个，现在只有1-2个了\n眼睛比较舒服了，有感觉比较有休息到\n吃了两个月感觉眼睛有进步很多\n老公眼睛红，最近也比较好了，比较少了",
"cat": "good",
"date": "02/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "0124268836\n吃一个月有变清楚，医生有讲黄斑好很多",
"cat": "good",
"date": "02/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "黄斑病变, 眼睛清楚",
"issue": "",
"attachment": ""
},
{
"text": "鸡皮肤",
"cat": "keyword",
"date": "02/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "头皮有痘痘可以用吗",
"cat": "keyword",
"date": "02/03/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "已经秃頭了还有效嗎？serious alopecia areta",
"cat": "keyword",
"date": "03/03/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "再试多几天吧伤口有硬化了",
"cat": "good",
"date": "03/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "伤口",
"issue": "",
"attachment": "IMG_8980.JPEG"
},
{
"text": "0194133963\n现在不用戴老花眼镜也可以看到了",
"cat": "good",
"date": "04/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "老花",
"issue": "",
"attachment": ""
},
{
"text": "请问斑秃脱发有效果吗",
"cat": "keyword",
"date": "05/03/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "验到眼角根很鄒  不提意开刀 风险大  要整天滴三次药水",
"cat": "keyword",
"date": "05/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼翳",
"cat": "keyword",
"date": "05/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼角膜破了可以恢复？",
"cat": "keyword",
"date": "06/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "15岁小孩子有糖尿病，要保养眼睛",
"cat": "keyword",
"date": "06/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "Already consumed 3 days.. still have floaters but can see clearer on laptop / hp screen",
"cat": "good",
"date": "11/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "眼睛清楚",
"issue": "",
"attachment": "屏幕截图 2026-03-11 182523.png"
},
{
"text": "紅班痕疡𝚂𝙻𝙴",
"cat": "keyword",
"date": "15/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "龟裂皮肤问题",
"cat": "keyword",
"date": "17/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼袋没有那么肿了..眼睛比以前亮了",
"cat": "good",
"date": "18/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "眼袋",
"issue": "",
"attachment": "IMG_9296.JPEG"
},
{
"text": "移植眼角膜",
"cat": "keyword",
"date": "20/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我喝这个有帮助失眠，喝了是真的很好睡，皮肤慢慢看是有比较白了啦",
"cat": "good",
"date": "20/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "左右颈项都有好转😍😍",
"cat": "good",
"date": "07/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "IMG_9332.JPEG"
},
{
"text": "我的腳底，脫皮硬硬的會好嗎？",
"cat": "keyword",
"date": "23/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "咀唇乾烈",
"cat": "keyword",
"date": "22/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "皮肤薄，容易括伤出现瘀血问题",
"cat": "keyword",
"date": "22/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "富贵手",
"cat": "good",
"date": "24/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "富贵手",
"issue": "",
"attachment": "富贵手.jpeg"
},
{
"text": "真的好产品，我喝了多瓶，皮肤变得好光滑和亮丽",
"cat": "good",
"date": "25/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "IMG_9440.JPEG"
},
{
"text": "有皮肤病，两个星期就没有痒和恢复美美的皮肤",
"cat": "good",
"date": "25/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "IMG_9443.JPEG,IMG_9444.JPEG"
},
{
"text": "对皮肤保健有效！",
"cat": "good",
"date": "25/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "da8a7231-3d44-4fd0-8603-416b570f6c14.JPEG"
},
{
"text": "这个真的很好.我的脚开刀伤口很大.我喝了一瓶半我的伤口好了7788",
"cat": "good",
"date": "25/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "伤口",
"issue": "",
"attachment": "828778d8-3454-4eea-8fef-4638e14f1f4c.JPEG"
},
{
"text": "FSH 44喝这个月经可以恢复正常吗（FSH 44 代表身体已经开始进入 更年期阶段，卵巢功能比较弱了，所以月经可能会变得不规律，甚至慢慢减少）",
"cat": "keyword",
"date": "24/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": "Screenshot 2026-03-26 at 12.23.34 PM.png"
},
{
"text": "我女儿一直来月经  来不停哦有时贫血，头晕",
"cat": "keyword",
"date": "25/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我平时月经是很准的， 上个月突然很少， 这个月迟了， 这几天有褐色又看不到血， 我怕失调",
"cat": "keyword",
"date": "25/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "I drank previously and i successfully pregnant\nDrank like 4 tin\nNow i have issue on skin and quite some pimple\nWan to tiao li my internal body",
"cat": "good",
"date": "26/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "4罐",
"effect": "备孕",
"issue": "",
"attachment": "备孕.png"
},
{
"text": "眼睛👀看到兩个影子",
"cat": "keyword",
"date": "26/03/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "排卵不了",
"cat": "keyword",
"date": "26/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "0126291831\n红斑红点慢慢消了\n尿道炎的问题也有感觉减轻了",
"cat": "good",
"date": "26/03/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "斑斑",
"issue": "",
"attachment": "屏幕截图 2026-03-26 191008.png"
},
{
"text": "喝了两瓶，对皮肤过敏有帮助。",
"cat": "good",
"date": "26/03/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "皮肤敏感",
"issue": "",
"attachment": "屏幕截图 2026-03-26 213329.png"
},
{
"text": "这能调理，和改善淋巴细胞吗？\n我的淋巴细胞指数一直不达标，很低，红血球也不理想，人总觉得累",
"cat": "keyword",
"date": "27/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼睛double vision",
"cat": "keyword",
"date": "28/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "白内障镭射过了，眼睛很不舒服，一直有很多眼屎",
"cat": "keyword",
"date": "28/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "血濃可以喝…有效?",
"cat": "keyword",
"date": "29/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "皮肤有变好，眼袋有效",
"cat": "good",
"date": "29/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "眼袋, 美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-03-29 160652.png"
},
{
"text": "Still dry but hv lesser",
"cat": "good",
"date": "30/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-03-30 092256.png"
},
{
"text": "给老公吃2个星期眼膜有消失看东西清楚很多了",
"cat": "good",
"date": "30/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "眼睛清楚",
"issue": "",
"attachment": "屏幕截图 2026-03-30 092223.png"
},
{
"text": "finished 3 boxes and I can see some improvement",
"cat": "good",
"date": "30/03/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-03-30 142453.png"
},
{
"text": "不过喝了真的痛经没那么疼了\n也比较准来\n这个月的经期量也多",
"cat": "good",
"date": "31/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "2024到现在",
"effect": "月经量少, 准时",
"issue": "",
"attachment": "Screenshot 2026-03-31 at 1.06.57 PM.png"
},
{
"text": "601111291543：飞蚊症少了，因为青光眼 验眼睛没有眼压了 左边12 右边13 觉得没有眼压已经很好了",
"cat": "good",
"date": "01/04/2026",
"product": "NE",
"who": "celynn",
"duration": "11盒 跟老公一起吃 保养",
"effect": "飞蚊症, 眼压",
"issue": "",
"attachment": ""
},
{
"text": "子宫腺肌症患者（本来应该长在子宫里面的子宫内膜组织，跑进了子宫肌肉层里面生长，因为这些组织每个月还是会跟着月经变化、出血，就会让子宫变厚、变硬，会导致疼痛） 通常都会有这些症状\n\n月经痛越来越严重\n经血量很多、经期变长\n下腹坠痛或腰酸\n经期前后都不舒服\n有些人会影响怀孕\n\n子宫会变厚、收缩不好，月经血排出时比较不顺就容易导致血块/经血量变多的",
"cat": "keyword",
"date": "01/04/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼睛没那么干，对手机的时间不能太久。我现在一次吃两条，一条效果没那么好。",
"cat": "good",
"date": "01/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": ""
},
{
"text": "吃了两个星期了,好多了,夜晚开车对面灯光不会变长形",
"cat": "good",
"date": "01/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-01 225510.png"
},
{
"text": "鼻子豆巴印",
"cat": "keyword",
"date": "01/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼晴没那么干了、也没那么容易累… 不过看东西还是有点矇糊🥹",
"cat": "good",
"date": "02/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": ""
},
{
"text": "风膜",
"cat": "keyword",
"date": "02/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "毛囊炎可以吗",
"cat": "keyword",
"date": "03/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "手的班少了",
"cat": "good",
"date": "04/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "斑斑",
"issue": "",
"attachment": "屏幕截图 2026-04-04 193402.png"
},
{
"text": "皮肤敏感有些改善",
"cat": "good",
"date": "04/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "皮肤敏感",
"issue": "",
"attachment": "屏幕截图 2026-04-04 221742.png"
},
{
"text": "右眼球下半段遮住看不见了",
"cat": "keyword",
"date": "05/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "night vision not clear",
"cat": "keyword",
"date": "06/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "眼睛清楚",
"issue": "",
"attachment": ""
},
{
"text": "眼睛没那么干，对手机的时间不能太久。我现在一次吃两条，一条效果没那么好。",
"cat": "good",
"date": "06/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "Screenshot 2026-04-01 at 2.39.41 PM.png"
},
{
"text": "如.有白癜風患者，喝可以治療有效果嗎?可以塗嗎？",
"cat": "keyword",
"date": "07/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我现在喝着.感觉很好",
"cat": "good",
"date": "08/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "皮肤病好了",
"cat": "good",
"date": "08/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "屏幕截图 2026-04-08 232158.png"
},
{
"text": "感觉眼袋小了一点，朋友还以为我做眼睛，感觉比以前眼睛明亮，喝了皮肤有比较好",
"cat": "good",
"date": "09/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶1盒",
"effect": "眼袋",
"issue": "",
"attachment": ""
},
{
"text": "真的很好，1瓶还没喝完皮肤好了",
"cat": "good",
"date": "09/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "IMG_9706.JPEG"
},
{
"text": "发现脸的皮肤伤口很快好，而且不留疤。也不容易变成发炎",
"cat": "good",
"date": "09/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "第二瓶",
"effect": "伤口",
"issue": "",
"attachment": "屏幕截图 2026-04-09 171906.png"
},
{
"text": "脸上斑有淡了一些",
"cat": "good",
"date": "09/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "三个月左右",
"effect": "斑斑",
"issue": "",
"attachment": "屏幕截图 2026-04-09 213207.png"
},
{
"text": "蚊子淡了点",
"cat": "good",
"date": "10/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "飞蚊症",
"issue": "",
"attachment": "屏幕截图 2026-04-10 161015.png"
},
{
"text": "Got some new baby hair & slightly less hair fall",
"cat": "good",
"date": "10/04/2026",
"product": "Fior",
"who": "celynn",
"duration": "4盒",
"effect": "掉发",
"issue": "",
"attachment": "Screenshot 2026-04-10 at 6.50.56 PM.png"
},
{
"text": "ok哦 这次period也没疼痛了 平时痛到不能起来 😰",
"cat": "good",
"date": "10/04/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "经痛",
"issue": "",
"attachment": "Screenshot 2026-04-10 at 6.57.44 PM.png"
},
{
"text": "过敏有慢慢的改善",
"cat": "good",
"date": "11/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "皮肤敏感",
"issue": "",
"attachment": "屏幕截图 2026-04-11 213944.png"
},
{
"text": "51岁，我刚来了一点红了，我停止了好多个月从十二月，好像也是十一号前后\n今天第二天月经正常来鲜红色也有些一点血块.",
"cat": "good",
"date": "11/04/2026",
"product": "JUJI",
"who": "celynn",
"duration": "1盒",
"effect": "更年期姨妈来了",
"issue": "",
"attachment": "Screenshot 2026-04-11 at 3.20.28 PM.png"
},
{
"text": "Diamond drink是真的，我的脚不能走的，就不能走，也不能站久，我喝了有1个星期-2个星期，现在我的脚很勤力，又能走了，可以走了很好，我有一点精神了，真的很好，我还要订",
"cat": "good",
"date": "12/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "2个星期",
"effect": "精神",
"issue": "",
"attachment": "9afac95f-8f4d-4408-9d5c-a0d4496fbaea.mp4"
},
{
"text": "我不知道是自己的心態還是怎麼樣，我喝了之後，濕疹有減輕了。如果有抓癢的話，也沒有那麼容易像之前那樣敏感，傷口流血，起紅點",
"cat": "good",
"date": "13/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "1个月",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "屏幕截图 2026-04-13 182448.png"
},
{
"text": "月经黑色的",
"cat": "keyword",
"date": "14/04/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我先让我先生和我姐试吃。目前我先生已经喝10天左右，他跟我说感觉眼睛没有那么干",
"cat": "good",
"date": "15/04/2026",
"product": "NE",
"who": "celynn",
"duration": "10天",
"effect": "干眼症",
"issue": "",
"attachment": "Screenshot 2026-04-15 at 10.34.41 AM.png"
},
{
"text": "喝到第二瓶是皮肤敏感有比较好，比较不痒",
"cat": "good",
"date": "15/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "第二瓶",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "屏幕截图 2026-04-15 223253.png"
},
{
"text": "脚可以弯了",
"cat": "good",
"date": "16/04/2026",
"product": "KHH",
"who": "celynn",
"duration": "3盒",
"effect": "膝盖",
"issue": "",
"attachment": "Screenshot 2026-04-16 at 12.03.09 PM.png"
},
{
"text": "皮肤有亮，精神也有提升",
"cat": "good",
"date": "16/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好, 精神",
"issue": "",
"attachment": "IMG_9854.JPEG"
},
{
"text": "Eye lids and neck area actually got eczema and dry after drink for 2 week it heal，Feel that my face like slightly more firm too",
"cat": "good",
"date": "17/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "2week",
"effect": "湿疹/皮肤痒, 美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-04-17 180731.png"
},
{
"text": "很好睡，比较有精神",
"cat": "good",
"date": "17/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "精神",
"issue": "",
"attachment": "屏幕截图 2026-04-17 214153.png"
},
{
"text": "眼睛没那么干了，飞蚊症也有好点",
"cat": "good",
"date": "18/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症, 飞蚊症",
"issue": "",
"attachment": "屏幕截图 2026-04-18 181356.png"
},
{
"text": "富貴手好了，很多臉也亮了很多",
"cat": "good",
"date": "21/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "两个星期",
"effect": "美白/皮肤好, 富贵手",
"issue": "",
"attachment": "屏幕截图 2026-04-21 124231.png"
},
{
"text": "眼睛没那么干了，也比之前舒服一点，就有时还是会朦下朦下",
"cat": "good",
"date": "21/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-04-21 140543.png"
},
{
"text": "有一点点改善，眨眼时眼睛不觉得有一层东西卡着.希望会慢慢改善",
"cat": "good",
"date": "21/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-04-21 151227.png"
},
{
"text": "医生说有看到一点效果",
"cat": "good",
"date": "21/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "伤口",
"issue": "",
"attachment": "屏幕录制 2026-04-21 215709.mp4"
},
{
"text": "皮肤斑斑淡化了",
"cat": "good",
"date": "23/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "斑斑",
"issue": "",
"attachment": "photo_6291915596320411511_y.jpg"
},
{
"text": "以前是这样的, 肿胀得很痛又痒痒的,有时会流浓或流血水，现在皮肤乾水了, 没有再悪化，比较好点了。",
"cat": "good",
"date": "23/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "伤口",
"issue": "",
"attachment": "photo_6291915596320411725_y.jpg,photo_6291915596320411726_y.jpg"
},
{
"text": "家人说好了大概70%，以前皮肤痒，喝了Diamond Drink 之后改善很多哦",
"cat": "good",
"date": "23/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "photo_6291915596320411743_y.jpg"
},
{
"text": "其实我是没有什么感觉有什么改变到啦，只是我女儿发现我的皮肤比之前亮了一下黑眼圈也有比较浅了",
"cat": "good",
"date": "24/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "眼袋, 美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-04-24 095649.png"
},
{
"text": "手皮肤薄，摩擦了容易出现积血情况",
"cat": "keyword",
"date": "24/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "好的，谢谢你，我的皮肤有细致许多，脸上的黑斑也有浅了一些，效果是蛮不错的，真心觉得不错的产品，谢谢🥰🥰",
"cat": "good",
"date": "24/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "斑斑, 美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "牛皮癣没有那么严重了 喝了3瓶！",
"cat": "good",
"date": "25/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "牛皮癣",
"issue": "",
"attachment": "photo_6298344354908671642_x.jpg"
},
{
"text": "请问有CRVO的客户见证吗",
"cat": "keyword",
"date": "30/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "斑有淡",
"cat": "good",
"date": "04/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "斑斑",
"issue": "",
"attachment": "屏幕录制 2026-05-03 121202.mp4"
},
{
"text": "其实之前喝了3瓶，看到皮肤有点改善，痒的范围缩小了。所以才选择继续喝的。",
"cat": "good",
"date": "07/05/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "屏幕截图 2026-05-07 162630.png"
},
{
"text": "本身开过刀，皮肤很干燥，喝了3瓶后，皮肤没那么脆弱，皮肤比较有水分，没那么干燥，胃胀风不舒服喝下去，马上改善",
"cat": "good",
"date": "08/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "",
"attachment": "ggggg.mp4"
},
{
"text": "老人家皮肤薄 脚生鸡眼",
"cat": "keyword",
"date": "10/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "眼睛确是不干了，黄斑 飞蚊 也改善很多，眼睛也舒服多了",
"cat": "good",
"date": "11/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "黄斑病变, 飞蚊症, 干眼症",
"issue": "",
"attachment": "屏幕截图 2026-05-11 155202.png"
},
{
"text": "黄斑还是有，但是看东西比较清楚一点了",
"cat": "good",
"date": "11/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "眼睛清楚",
"issue": "",
"attachment": "屏幕截图 2026-05-12 121915.png"
},
{
"text": "看东西有比较舒服点",
"cat": "good",
"date": "11/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-05-12 121923.png"
},
{
"text": "皮肤一檫就会发黑，可以服用吗？",
"cat": "keyword",
"date": "11/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "东马邮寄3天收到",
"cat": "good",
"date": "13/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕录制 2026-05-13 130936.mp4"
},
{
"text": "味道好",
"cat": "good",
"date": "20/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "IMG_0372.JPEG"
},
{
"text": "眼睛不很干了。飞蚊小了。",
"cat": "good",
"date": "21/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症, 飞蚊症",
"issue": "",
"attachment": "屏幕截图 2026-05-21 220117.png"
},
{
"text": "有时不用戴老花眼镜也可以看得清楚些，飞蚊呢有时少一点点有时会没有",
"cat": "good",
"date": "21/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "飞蚊症, 眼睛清楚",
"issue": "",
"attachment": "屏幕截图 2026-05-21 220440.png"
},
{
"text": "就是眼睛有血才找nutrieye, nutrieye 有说到可以吃， 就试试，过后到回去看医生，医生说血丝减少了，就多多的鼓励她继续吃，现在他又说会痒又濛会痛。",
"cat": "good",
"date": "23/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "干眼症",
"issue": "",
"attachment": "屏幕截图 2026-05-23 204216.png"
},
{
"text": "我儿子讲味道好喝",
"cat": "good",
"date": "21/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "IMG_0379.JPEG"
},
{
"text": "味道很好能够接受",
"cat": "good",
"date": "",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-05-24 164746.png"
},
{
"text": "👍好喝。孙子喜欢喝。皮肤也好了很多没有那么痒了",
"cat": "good",
"date": "03/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": "屏幕截图 2026-06-03 191942.png"
},
{
"text": "很好，喝了皮肤好很多了，我也介绍给我妹妹她们喝，她们也说很好，真的很好 给你们大大个赞👍",
"cat": "good",
"date": "03/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "湿疹/皮肤痒, 牛皮癣",
"issue": "",
"attachment": "屏幕截图 2026-06-03 200823.png"
},
{
"text": "好喝。皮肤滑嫩了。女儿15可以喝吗？",
"cat": "good",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "Hi, 已经喝了5瓶，味道很好喝，我觉得喝了皮肤有点白，其实要喝多久才有效果。",
"cat": "good",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "5瓶",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "已经服用。皮肤有变得比较白，没这么暗淡。",
"cat": "good",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "味道好喝, 喝了对皮肤敏感有改善",
"cat": "good",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "皮肤敏感",
"issue": "",
"attachment": ""
},
{
"text": "眼睛根流血。不过己经手术了。",
"cat": "keyword",
"date": "04/06/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "下午好！我已经服用了几个月，味道不错，效果也很好，脸上的斑淡化了很多，有些也消失了，脸部也提亮了。",
"cat": "good",
"date": "10/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "斑斑, 美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "味道不错，搞到我很想喝多几杯，功效还好。身体上没那么痒了。还要一段时间才知道 有没有改善？",
"cat": "good",
"date": "",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "皮肤敏感",
"issue": "",
"attachment": ""
},
{
"text": "飞蚊症减少。如果少看手机会更好，没办法这个年代没手机不行😁",
"cat": "good",
"date": "10/06/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "飞蚊症",
"issue": "",
"attachment": "Screenshot 2026-06-10 at 1.47.15 PM.png"
},
{
"text": "我之前没有拍照，不过用了Fior的产品之后（到目前第四盒了），每天洗头时已经很少掉头发了，baby hair也生了很多，不知道还要继续再用产品吗？",
"cat": "good",
"date": "12/06/2026",
"product": "Fior",
"who": "celynn",
"duration": "四盒",
"effect": "baby hair",
"issue": "",
"attachment": "Screenshot 2026-06-22 at 3.20.14 PM.png"
},
{
"text": "已经开始喝了，味道很好，不甜不腻不酸",
"cat": "good",
"date": "14/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-06-14 094513.png"
},
{
"text": "脸感觉比较亮了",
"cat": "good",
"date": "15/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "1瓶",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-06-15 213718.png"
},
{
"text": "喝了十天，味道不错。目前皮肤敏感有改善，希望再过几天全身痒会完全消失。这个痒真的很折磨和煎熬，痒到怀疑人生。谢谢！",
"cat": "good",
"date": "17/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "10天",
"effect": "皮肤敏感",
"issue": "",
"attachment": ""
},
{
"text": "喝了女儿说脸上的青春豆好多了",
"cat": "good",
"date": "18/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "两个星期",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-06-18 233144.png"
},
{
"text": "飞蚊症改善",
"cat": "good",
"date": "19/06/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "飞蚊症",
"issue": "",
"attachment": "Screenshot 2026-06-17 at 3.13.36 PM.png"
},
{
"text": "其实里面的成分是什么？我一直都在给中医调理，最近经期有点乱，三个月中开始就没有来，中医都没有效，但是今天我经期来一点了，感觉不可思议，怎么比中药针灸更有效!?",
"cat": "good",
"date": "23/06/2026",
"product": "JUJI",
"who": "celynn",
"duration": "两个星期",
"effect": "更年期姨妈来了",
"issue": "",
"attachment": "更年期 来了一点.png"
},
{
"text": "脱发有减少一点, 出油也少了....其他还在观察",
"cat": "good",
"date": "29/06/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "出油问题, 掉发",
"issue": "",
"attachment": "Screenshot 2026-06-29 at 11.51.05 AM.png"
},
{
"text": "有改善出油问题",
"cat": "good",
"date": "",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "出油问题",
"issue": "",
"attachment": "改善出油问题.png"
},
{
"text": "有减少掉发，继续观察 \n你好頭皮是ok 脱发没掉那么多\n请问每天洗頭可以嗎？baby发有生不是很多",
"cat": "good",
"date": "29/06/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "掉发",
"issue": "",
"attachment": ""
},
{
"text": "味道不错，我从17号晚上开始喝，有帮助到我的睡眠👍前2天我心脏有点痛不懂是不是帮我调理,小时候跌倒过😂想问一下是不是也能帮助到小时候跌倒的伤口👍",
"cat": "good",
"date": "28/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "12天",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "很好我吃了眼睛己经幾个月都没打针了不错很好我会继續吃",
"cat": "good",
"date": "03/07/2026",
"product": "NE",
"who": "Jiaying",
"duration": "",
"effect": "黄斑病变",
"issue": "",
"attachment": "屏幕截图 2026-07-03 202127.png"
},
{
"text": "皮肤比较干燥",
"cat": "keyword",
"date": "04/07/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "OK👌，我的飞蚊症已有十多年我今天发现已经开始黑色开始淡化了",
"cat": "good",
"date": "04/07/2026",
"product": "NE",
"who": "Jiaying",
"duration": "3天",
"effect": "飞蚊症",
"issue": "",
"attachment": "屏幕截图 2026-07-04 165322.png"
},
{
"text": "我那时候可能才喝2-3天吧🤔感觉起床的时候眼睛分泌物没那么多了，因为我熬夜很夸张😆\n然后连续喝了几天皮肤感觉摸起来比较滑，法令纹暗沉的部分也是有改善，不会那么暗沉了～",
"cat": "good",
"date": "05/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-07-05 215326.png"
},
{
"text": "你是第一个会问我味道还喜欢吗？其实你们的产品我\n已经喝了两年多了 只有你一个会问我味道如何喝到怎\n样其他人只是要做生意叫我下单什么也不会问 你的\n服务",
"cat": "good",
"date": "02/07/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "味道",
"issue": "",
"attachment": "Screenshot 2026-07-02 at 3.59.00 PM.png"
},
{
"text": "想跟您说说，今天中午有来点红。\n19.03.2026没有来到现在来也·",
"cat": "good",
"date": "27/06/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "更年期姨妈来了",
"issue": "",
"attachment": "Screenshot 2026-06-27 at 10.50.54 PM.png"
},
{
"text": "After drinks my skin more better",
"cat": "good",
"date": "07/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": ""
},
{
"text": "皮肤好了",
"cat": "good",
"date": "07/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "屏幕录制 2026-07-07 201726.mp4"
},
{
"text": "斑斑有淡，但是皮肤还没好，目前喝了整整7个月",
"cat": "good",
"date": "07/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "斑斑",
"issue": "",
"attachment": "屏幕录制 2026-07-07 212324.mp4"
},
{
"text": "我爸爸买第1瓶喝 看到他有好",
"cat": "good",
"date": "07/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "1695.mp4"
},
{
"text": "Oh, my skin actually is ok. It's just last time I usually hve allergy. Now I never feel itchy or allergy anymore but I'm still taking the diamond drink. I still hve 3 bottles left. Thanks ya. I will continue to take it.",
"cat": "good",
"date": "08/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "湿疹/皮肤痒",
"issue": "",
"attachment": ""
},
{
"text": "皮肤有变白，每天早上一小杯还会继续保持下去",
"cat": "good",
"date": "09/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "2-3瓶",
"effect": "美白/皮肤好",
"issue": "",
"attachment": "屏幕截图 2026-07-09 091434.png"
},
{
"text": "3️⃣ 目前头皮没那么容易出油 掉发情况比之前好一点点",
"cat": "good",
"date": "08/07/2026",
"product": "Fior",
"who": "celynn",
"duration": "",
"effect": "出油问题, 掉发",
"issue": "",
"attachment": "Screenshot 2026-07-08 at 8.56.32 PM.png"
},
{
"text": "斑斑还是有在 没有消掉 e",
"cat": "bad",
"date": "",
"product": "DD",
"who": "",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "箱子有点破。还好里面的东西还在",
"cat": "bad",
"date": "",
"product": "DD",
"who": "",
"duration": "",
"effect": "",
"issue": "破掉",
"attachment": "破.jpg"
},
{
"text": "已经吃完了4盒，开始觉得有些改善，过后就没有了，非蚊症还是一样存在😓 飞蚊症10年了",
"cat": "bad",
"date": "",
"product": "NE",
"who": "celynn",
"duration": "4盒",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "沒什么進展。我覺得不是 NUTRIEYE 的問題而是我自己眼睛的問題。應該是糖尿病的事故造成我眼睛的视力越来越差了。\n3 年多了吧。靠打針 prevent blindness. 目没在打了。太贵了。—針差不多五六千",
"cat": "bad",
"date": "09/02/2026",
"product": "NE",
"who": "celynn",
"duration": "3盒",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "涂了仙人掌 就开始脱皮了（富贵手",
"cat": "bad",
"date": "12/02/2026",
"product": "DD",
"who": "Shihui",
"duration": "涂了10多天",
"effect": "",
"issue": "没效",
"attachment": "破皮.jpg"
},
{
"text": "吃完了。不过手指还是老样子，有点僵硬&疼😅 去年十一月才僵疼的，只是右手的三根手指",
"cat": "bad",
"date": "23/02/2026",
"product": "KHH",
"who": "celynn",
"duration": "喝了五盒",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "看起来比1开始更严重 开始1月22号喝 1个月多了，没什么好转，更严重了，脚一片一片都是",
"cat": "bad",
"date": "27/02/2026",
"product": "DD",
"who": "Shihui",
"duration": "1个月多",
"effect": "",
"issue": "没效",
"attachment": "bb.jpg,bv.jpg,bn.jpg"
},
{
"text": "很甜",
"cat": "bad",
"date": "02/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我喝了之后来很多白带。然后之后呢来完白带之后，我喝完那一支刚刚好一个月。然后过几天我就来月经。我已经是收经的，没有来月经的了",
"cat": "bad",
"date": "24/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "1瓶",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-03-24 174243.png"
},
{
"text": "已经喝 jujigrainz 差不多6个月了 为什么姨妈还是不准时 量还是少的呢？",
"cat": "bad",
"date": "25/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "没效",
"attachment": "Screenshot 2026-03-26 at 12.21.18 PM.png"
},
{
"text": "我吃了这么久，9月喝，2月才来一次，一点点而已。到现在就没来 48岁",
"cat": "bad",
"date": "26/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "3罐",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "喝完1盒没有见效 飞蚊护视力",
"cat": "bad",
"date": "27/03/2026",
"product": "NE",
"who": "celynn",
"duration": "1盒",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "没有效果的产品，喝了3瓶一点点都没有帮助到，皮肤病更痒，眼袋都没有消失",
"cat": "bad",
"date": "29/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "IMG_9521.JPEG"
},
{
"text": "完全没有效果，现在脸长更多痘痘，非常痒",
"cat": "bad",
"date": "29/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "10瓶",
"effect": "",
"issue": "没效",
"attachment": "ppp.png"
},
{
"text": "眼袋我吃了都不会小",
"cat": "bad",
"date": "30/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "1年",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "备孕1年了",
"cat": "bad",
"date": "31/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": "Screenshot 2026-03-31 at 4.54.58 PM.png"
},
{
"text": "我喝了差不多3罐，可是效果还没看到是正常的吗？ 量少",
"cat": "bad",
"date": "31/03/2026",
"product": "JUJI",
"who": "celynn",
"duration": "3罐",
"effect": "",
"issue": "没效",
"attachment": "Screenshot 2026-03-31 at 4.59.22 PM.png"
},
{
"text": "我喝了这个做化疗都没有帮到的",
"cat": "bad",
"date": "31/03/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "吃了这几盒眼睛会比較妥一点只是没什么大改善，左边的一支眼睛还是有亮不出来",
"cat": "bad",
"date": "01/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "飛蚊症還有（2年",
"cat": "bad",
"date": "02/04/2026",
"product": "NE",
"who": "celynn",
"duration": "1个月多",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "喝了和涂反而越来越严重 没有好，所以只单单涂仙人掌 才好多了，可是现在还是反反复复",
"cat": "bad",
"date": "03/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶，3盒，5瓶cactus gel",
"effect": "",
"issue": "",
"attachment": "WhatsApp Image 2026-04-03 at 2.10.31 PM.jpeg"
},
{
"text": "医生说伤口有变大了一点，但是皮肤有变好",
"cat": "bad",
"date": "05/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "第一买的较浓，第二次买的很水，涂在手全部水份较多，仙人掌成份很少\n之前图的粘粘的，现在涂在手很快就干",
"cat": "bad",
"date": "05/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我停止喝diamond drink 之后，湿疹更严重了。以前只是手而已，现在脚和身体都有",
"cat": "bad",
"date": "06/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "皮肤痒 斑斑 喝了没有效果",
"cat": "bad",
"date": "09/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶2盒",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-09 154429.png"
},
{
"text": "淡 一点都不浓缩，和之前的差超级多 很假",
"cat": "bad",
"date": "12/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "IMG_9802.JPEG"
},
{
"text": "廣告打到太離普，喝了―『星期又白又美讲到天上有地上無，听到生气，我也是有喝我2月27号开始喝喝了2支皮膚沒改善呀，还有2支沒开，保健",
"cat": "bad",
"date": "13/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "老花没什么效果",
"cat": "bad",
"date": "14/04/2026",
"product": "NE",
"who": "Jiaying",
"duration": "3盒",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-14 160118.png,屏幕截图 2026-04-14 155935.png"
},
{
"text": "喝了6-7瓶，没效果",
"cat": "bad",
"date": "14/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "6-7瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-14 160143.png"
},
{
"text": "之前好像50sen 现在发大两倍 还一直很很很痒",
"cat": "bad",
"date": "14/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "1瓶半",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-14 170304.png"
},
{
"text": "感觉一样，喝了没什么改变",
"cat": "bad",
"date": "16/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-16 111737.png"
},
{
"text": "我喝三罐一合，眼袋手班班还是有",
"cat": "bad",
"date": "16/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶+1盒",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-16 161828.png"
},
{
"text": "I brought some many bottles not effective",
"cat": "bad",
"date": "16/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-16 230041.png"
},
{
"text": "喝了会累，想睡觉",
"cat": "bad",
"date": "17/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "5天",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-17 180416.png"
},
{
"text": "I hav taking 1  week oledi, coughing on n off , period can take? I keep feeling sleepy",
"cat": "bad",
"date": "07/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "1 week",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-17 221310.png"
},
{
"text": "每晚喝了胸前和脛前都会痒（本身没有敏感问题）",
"cat": "bad",
"date": "18/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "一个星期",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-18 084931.png"
},
{
"text": "请问我已经喝了已经也14天了，我的整个脸变暗沉去，是不是产品不适合，请问有什么问题吗",
"cat": "bad",
"date": "20/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "14天",
"effect": "",
"issue": "没效",
"attachment": "IMG_9947.JPEG"
},
{
"text": "喝了9个月还是有看到斑点。不懂是不是黑点太顽固了",
"cat": "bad",
"date": "21/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "9个月",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-21 155434.png,屏幕截图 2026-04-21 154110.png"
},
{
"text": "痘痘痘印还是一样 都喝完了 三盒",
"cat": "bad",
"date": "21/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "三盒",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-21 135826.png"
},
{
"text": "我吃完了，效果不是很好。我现在吃另外一种很不錯，幫到我的眼睛👍",
"cat": "bad",
"date": "23/04/2026",
"product": "NE",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "Hi. 眼睛不干，但飞蚊和白膜没改善。。。。",
"cat": "bad",
"date": "23/04/2026",
"product": "NE",
"who": "celynn",
"duration": "3盒",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "嗨，你好，请问我买过2次，之前喝了3瓶，喝之前有摇一下，倒出来是有少许的泡沫，微酸甜。\n现在喝第四瓶，没有泡沫，味道虽然OK,不过没有之前的这么好，exp.date;是07/2027。\n请问效果会相差吗？因为这个like酵素drink,没有泡沫，就品质没这么好，有点小担心",
"cat": "bad",
"date": "24/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-24 132218.png"
},
{
"text": "这次的产品品质变薄了😤",
"cat": "bad",
"date": "25/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-25 110156.png"
},
{
"text": "Hi, I had purchased your Diamond Drink and I wish to complain that after taking it for 3 nights, I find that cellulite accumulate on my thighs, arms and face puffy. These symptoms similar like I took collagen of a few  brands. My body absorb supplement very fast and see results. Nowadays I dare not take collagen supplement as symptoms mentioned above occur. May I know why this happen to me? Last night I didn't continue talking your product.",
"cat": "bad",
"date": "26/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-26 135524.png"
},
{
"text": "喝了两罐还是痒",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-27 131639.png"
},
{
"text": "喝了没什么郊果",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-27 134403.png"
},
{
"text": "还有,可是没什么感觉",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-27 135016.png"
},
{
"text": "差不多喝完了，但是没有效果。反而发大了3倍",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-27 142058.png"
},
{
"text": "我觉得之前的比較濃的，这次买的很像水樣",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-04-27 142731.png"
},
{
"text": "我要投诉 已经喝这產品6罐完了雀斑都不见效皮肤痒也不见好!花了千馀元买这產品心疼极了!",
"cat": "bad",
"date": "27/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "喝等3支 没改变",
"cat": "bad",
"date": "28/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-28 131514.png"
},
{
"text": "no prominent result after taking for so many months",
"cat": "bad",
"date": "28/04/2026",
"product": "DD",
"who": "Shihui",
"duration": "9瓶2盒",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-28 194250.png"
},
{
"text": "喝完三瓶，没有感觉任何效果 是不是要买很多很多瓶来喝，才有效果，眼睛老花依旧",
"cat": "bad",
"date": "29/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-29 171854.png"
},
{
"text": "我喝了2瓶 没效果",
"cat": "bad",
"date": "29/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "2瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-29 175831.png"
},
{
"text": "It's been one month. I see no improvement for my skin so far",
"cat": "bad",
"date": "30/04/2026",
"product": "DD",
"who": "Jiaying",
"duration": "一个月",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-04-30 220310.png"
},
{
"text": "我已经快喝完一瓶，但是为什么会比以前更繁密，之前是在腿上发痒，只希望喝了不再复发，但是现在我的颈项却开始痒？？？",
"cat": "bad",
"date": "04/05/2026",
"product": "DD",
"who": "Jiaying",
"duration": "一瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-05-04 114406.png"
},
{
"text": "我觉得我吃了还是有飞蚊症",
"cat": "bad",
"date": "05/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "半年",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-05-05 125330.png"
},
{
"text": "为什么 有这样多平台？我们会怕买到假货",
"cat": "bad",
"date": "06/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-05-06 135537.png"
},
{
"text": "仙人掌涂了后，早上白白一片的",
"cat": "bad",
"date": "07/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕录制 2026-05-07 095819.mp4"
},
{
"text": "I used 3 bottles, useless\nThat is just small 20 sen size, use med cream...nothing to do q dis as well...but my whole body skin texture didn't seem improvement",
"cat": "bad",
"date": "07/05/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-05-07 170945.png,屏幕截图 2026-05-07 170950.png,屏幕截图 2026-05-07 170955.png"
},
{
"text": "我从11月开始喝到现在我都怀疑人生了， 斑还在… 不知道是否要继续下去",
"cat": "bad",
"date": "11/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "11/2025-5/2026",
"effect": "",
"issue": "没效",
"attachment": "IMG_0305.JPEG"
},
{
"text": "眼睛看东西还是蒙看电话的字不清楚",
"cat": "bad",
"date": "12/05/2026",
"product": "NE",
"who": "Jiaying",
"duration": "大概一个月半",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-05-12 121704.png"
},
{
"text": "喝了斑斑有变淡，停喝后又来了",
"cat": "bad",
"date": "13/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "",
"attachment": "屏幕录制 2026-05-13 105605.mp4"
},
{
"text": "这个送货的这样放也可以吗？等下跌下来，也没有call",
"cat": "bad",
"date": "20/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "顾客.jpeg"
},
{
"text": "没有信心了，吃了6瓶，也没有改善！",
"cat": "bad",
"date": "24/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "6瓶",
"effect": "",
"issue": "没效",
"attachment": "IMG_0422.JPEG"
},
{
"text": "我其实吃了六罐 没有效果",
"cat": "bad",
"date": "24/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "6瓶",
"effect": "",
"issue": "没效",
"attachment": "IMG_0423.JPEG"
},
{
"text": "Day by day, it come more and more",
"cat": "bad",
"date": "27/05/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "32cc7887-b1d4-40b4-82ea-5925ae93a4c6.JPEG,79a59e49-49f5-4f84-a9ce-8cb72398cdd6.JPEG,IMG_0448.JPEG"
},
{
"text": "喝了8天 脸肿，手指肿，脚肿，昨晚停了肿就慢慢消了，因为之前我手指和脚有点关节疼痛",
"cat": "bad",
"date": "03/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "8天",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "Not effective! Tks!",
"cat": "bad",
"date": "03/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-03 183943.png"
},
{
"text": "喝了三瓶 完全沒有效喔",
"cat": "bad",
"date": "03/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-03 185131.png"
},
{
"text": "喝了，没看到效果",
"cat": "bad",
"date": "03/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3个月",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-03 190505.png"
},
{
"text": "我已经和了6个月什么效果都没有… 开始3个月配套没效果， 要我再加3个月！ 又再3个月过后又再劝3个月… 是一点小姑都没有",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "6个月",
"effect": "",
"issue": "没效",
"attachment": "IMG_0558.JPEG"
},
{
"text": "一共喝了5botts加2合.全部喝完.不是很理想.感觉太甜了.喝期间口干得很",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "5瓶2盒",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-06-04 105548.png"
},
{
"text": "味道可以接受，但是皮肤没什么变化",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "3个月",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "我老公喝了第三只眼袋没消",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "喝了4瓶没看到有什么改变斑还是那么深和多",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "已經第3瓶。沒什麼进展🤷‍♀️黑斑沒退沒减🫡",
"cat": "bad",
"date": "04/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-04 184216.png"
},
{
"text": "我想反映，在连续饮用贵公司的 Diamond 饮品两天后，我的血糖读数分别上升至 6.2 mmol/L 和 6.4 mmol/L，而我平时的日常血糖读数通常都低于 6.0 mmol/L。 烦请贵公司对此情况进行调查，并告知该产品中的任何成分是否可能导致血糖水平上升。 期待贵公司的回复，谢谢。",
"cat": "bad",
"date": "08/06/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-06-08 161719.png"
},
{
"text": "喝之前和现在没有多大分别",
"cat": "bad",
"date": "20/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "6瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-20 154938.png"
},
{
"text": "没什么效果黑班跟多",
"cat": "bad",
"date": "20/06/2026",
"product": "DD",
"who": "Jiaying",
"duration": "五个月",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-06-20 172738.png"
},
{
"text": "你们家的粉里有这个黑黑又硬的东西 像是木粹的",
"cat": "bad",
"date": "24/06/2026",
"product": "JUJI",
"who": "celynn",
"duration": "",
"effect": "",
"issue": "",
"attachment": "image.png"
},
{
"text": "包装有破损，导致引来一些蚂虫",
"cat": "bad",
"date": "20/06/2026",
"product": "",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": "image.png"
},
{
"text": "如果开了超过一个月，它会caking, 就是变硬\n品质问题？\n可以改进？",
"cat": "bad",
"date": "16/06/2026",
"product": "",
"who": "",
"duration": "",
"effect": "",
"issue": "",
"attachment": "Screenshot 2026-06-25 at 12.50.34 PM.png"
},
{
"text": "不需要问候了， 请把我的联系号码删除！ \n喝了100天➕100天真搞笑！ 果然一丁点效果都没有…. 别再来任何信息！ 把我联系删了",
"cat": "bad",
"date": "03/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "320天",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "一点点的改善都没看到。不要说改善，连控制这方面的改善都没看到。",
"cat": "bad",
"date": "04/07/2026",
"product": "DD",
"who": "Jiaying",
"duration": "8瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-07-04 145603.png,屏幕截图 2026-07-04 145612.png"
},
{
"text": "喝了，眼睛肿是正常的吗？",
"cat": "bad",
"date": "05/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "1瓶",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "没有效果，一直脱皮，没有痒",
"cat": "bad",
"date": "06/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "3瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕录制 2026-07-06 204843.mp4"
},
{
"text": "老实说，条状的会比瓶的效果好（皮肤没有那么干燥）",
"cat": "bad",
"date": "06/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "3个月",
"effect": "",
"issue": "",
"attachment": "屏幕截图 2026-07-06 205137.png,屏幕截图 2026-07-06 205121.png"
},
{
"text": "我老公喝到现在皮肤过敏问题还是没有改善，一直反反复复",
"cat": "bad",
"date": "07/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "4瓶",
"effect": "",
"issue": "没效",
"attachment": "屏幕截图 2026-07-07 162200.png"
},
{
"text": "我本来糖分5.2我喝了两支后糖分5.9就不敢再喝了",
"cat": "bad",
"date": "08/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶",
"effect": "",
"issue": "",
"attachment": ""
},
{
"text": "没有太大的改善",
"cat": "bad",
"date": "10/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "",
"effect": "",
"issue": "",
"attachment": "屏幕录制 2026-07-10 122441.mp4"
},
{
"text": "我是注重黑眼圈和眼袋，没有什么改善",
"cat": "bad",
"date": "13/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "70天",
"effect": "",
"issue": "没效",
"attachment": ""
},
{
"text": "Hi Alice, 你 好 ！没 什么 不 一样 ，斑 点 还 是 有 😆",
"cat": "bad",
"date": "13/07/2026",
"product": "DD",
"who": "Shihui",
"duration": "2瓶多",
"effect": "",
"issue": "没效",
"attachment": ""
}
]
