'use client'

import { useState } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useQueryClient } from '@tanstack/react-query'
import { orderSchema, type OrderFormData } from '@/lib/validations'
import {
  fetchCustomerByPhone, upsertCustomer, createOrder, generateOrderId,
} from '@/app/actions/data'
import { useProjects, type Package } from '@/lib/hooks/useProjects'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import { BRAND_COLORS } from '@/lib/constants'

const AUTO_ID_PROJECTS = ['DD', 'Juji', 'NE', 'FIOR', 'KHH']

const CHANNELS = [
  'FB', 'WhatsApp', 'Shopee', 'FB ENG', 'Lazada', 'Staff', 'WhatsApp ENG', 'Shopee SG',
] as const

interface Props { open: boolean; onClose: () => void }

function Req({ children }: { children: React.ReactNode }) {
  return <span>{children} <span className="text-red-500">*</span></span>
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">{children}</p>
}

export default function AddOrderModal({ open, onClose }: Props) {
  const queryClient = useQueryClient()
  const [loading, setLoading] = useState(false)
  const [lookingUp, setLookingUp] = useState(false)
  const [foundCustomerId, setFoundCustomerId] = useState<string | null>(null)
  const [foundCustomerName, setFoundCustomerName] = useState<string | null>(null)
  const [autoFilled, setAutoFilled] = useState<Set<string>>(new Set())
  const [generatingId, setGeneratingId] = useState(false)
  const [autoGeneratedId, setAutoGeneratedId] = useState<boolean>(false)
  const [priceAutoFilled, setPriceAutoFilled] = useState(false)
  const [newRepeatAutoFilled, setNewRepeatAutoFilled] = useState(false)

  const today = new Date().toISOString().split('T')[0]

  const { register, handleSubmit, setValue, watch, reset, control, formState: { errors } } = useForm<OrderFormData>({
    resolver: zodResolver(orderSchema),
    defaultValues: { status: 'pending', order_date: today, package_id: null },
  })

  const selectedProjectId = watch('project_id')

  const { projects } = useProjects()
  const projectPackages: Package[] = projects.find(p => p.id === selectedProjectId)?.packages ?? []

  const selectedProject = projects.find(p => p.id === selectedProjectId)
  const brandColor = selectedProject ? BRAND_COLORS[selectedProject.name] : null

  async function lookupPhone() {
    let phone = watch('customer_phone') ?? ''
    if (/^0\d/.test(phone)) {
      phone = '6' + phone
      setValue('customer_phone', phone)
    }
    if (!phone || phone.length < 8) return
    setLookingUp(true)
    const customer = await fetchCustomerByPhone(phone)
    if (customer) {
      setValue('customer_name', customer.name)
      setFoundCustomerId(customer.id)
      setFoundCustomerName(customer.name)
      setAutoFilled(new Set(['customer_name']))
      const orderCount = (customer as any).total_orders ?? 0
      setValue('is_new_customer', orderCount === 0)
      setNewRepeatAutoFilled(true)
    } else {
      setValue('is_new_customer', undefined as any)
      setFoundCustomerId(null)
      setFoundCustomerName(null)
      setAutoFilled(new Set())
      setNewRepeatAutoFilled(false)
    }
    setLookingUp(false)
  }

  async function handleProjectChange(projectId: string) {
    setValue('product_name', '')
    setValue('package_name', '')
    setValue('package_id', null)

    const proj = projects.find(p => p.id === projectId)
    if (proj && AUTO_ID_PROJECTS.includes(proj.name)) {
      setGeneratingId(true)
      setAutoGeneratedId(false)
      try {
        const newId = await generateOrderId(projectId)
        setValue('tracking_number', newId)
        setAutoGeneratedId(true)
      } catch (err) {
        console.error('Failed to generate order ID:', err)
        setValue('tracking_number', null)
        setAutoGeneratedId(false)
      } finally {
        setGeneratingId(false)
      }
    } else {
      setValue('tracking_number', null)
      setAutoGeneratedId(false)
    }
  }

  async function onSubmit(data: OrderFormData) {
    setLoading(true)
    try {
      let customerId = foundCustomerId
      if (!customerId && data.customer_phone) {
        customerId = await upsertCustomer(data.customer_name ?? '', data.customer_phone)
      }
      await createOrder({
        customer_id: customerId,
        project_id: data.project_id,
        package_id: data.package_id ?? null,
        product_name: data.product_name,
        package_name: data.package_name || null,
        total_price: data.total_price,
        status: data.status,
        order_date: data.order_date,
        fb_name: null,
        channel: data.channel,
        purchase_reason: data.purchase_reason || null,
        is_new_customer: data.is_new_customer ?? true,
        tracking_number: data.tracking_number ?? null,
        state: null,
        address: null,
      })
      toast.success('Order created')
      queryClient.invalidateQueries({ queryKey: ['orders'] })
      queryClient.invalidateQueries({ queryKey: ['dashboard'] })
      handleClose()
    } catch (e: any) {
      toast.error(e.message ?? 'Failed to create order')
    } finally {
      setLoading(false)
    }
  }

  function handleClose() {
    reset({ status: 'pending', order_date: today, package_id: null, tracking_number: null })
    setFoundCustomerId(null)
    setFoundCustomerName(null)
    setAutoFilled(new Set())
    setAutoGeneratedId(false)
    setPriceAutoFilled(false)
    setNewRepeatAutoFilled(false)
    onClose()
  }

  function handlePackageSelect(packageId: string) {
    if (packageId === 'none') {
      setValue('product_name', '')
      setValue('package_name', '')
      setValue('package_id', null)
      setValue('total_price', '' as any)
      setPriceAutoFilled(false)
      return
    }
    const pkg = projectPackages.find(p => p.id === packageId)
    if (!pkg) return
    setValue('product_name', pkg.name)
    setValue('package_name', pkg.name)
    setValue('package_id', pkg.id)
    if (pkg.price > 0) {
      setValue('total_price', pkg.price)
      setPriceAutoFilled(true)
    } else {
      setValue('total_price', '' as any)
      setPriceAutoFilled(false)
    }
  }

  function packageLabel(pkg: Package): string {
    const parts: string[] = []
    if (pkg.code) parts.push(`[${pkg.code}]`)
    parts.push(pkg.name)
    parts.push(`— RM ${pkg.price.toFixed(2)}`)
    return parts.join(' ')
  }

  const isAuto = (f: string) => autoFilled.has(f)
  const selectedPackageId = watch('package_id')

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader><DialogTitle>Add Order</DialogTitle></DialogHeader>

        {/* Brand selector + color pill */}
        <div className="space-y-1 -mt-1">
          <Controller name="project_id" control={control} render={({ field }) => (
            <Select value={field.value ?? ''} onValueChange={v => { field.onChange(v); handleProjectChange(v) }}>
              <SelectTrigger className={cn(brandColor && cn(brandColor.bg, brandColor.text, brandColor.border))}>
                <SelectValue placeholder="Select brand *" />
              </SelectTrigger>
              <SelectContent>
                {projects.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
              </SelectContent>
            </Select>
          )} />
          {errors.project_id && <p className="text-xs text-destructive">{errors.project_id.message}</p>}
          {generatingId && <p className="text-xs text-muted-foreground">Generating order ID…</p>}
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-3">

          {/* ── Section 1: Customer ───────────────────────────────────── */}
          <SectionLabel>Customer</SectionLabel>

          {/* Name */}
          <div className="space-y-1">
            <Label>名字</Label>
            <Input
              placeholder="Full name"
              {...register('customer_name')}
              className={cn(isAuto('customer_name') && 'text-red-600 border-red-200')}
            />
            {isAuto('customer_name') && <p className="text-xs text-red-500">Auto-filled from phone lookup</p>}
          </div>

          {/* Phone */}
          <div className="space-y-1">
            <Label>Phone No</Label>
            <Input
              placeholder="601xxxxxxxx"
              {...register('customer_phone', {
                onChange: e => {
                  if (!e.target.value.trim()) {
                    setValue('is_new_customer', undefined as any)
                    setFoundCustomerId(null)
                    setFoundCustomerName(null)
                    setNewRepeatAutoFilled(false)
                    setAutoFilled(new Set())
                  }
                },
              })}
              onBlur={lookupPhone}
            />
            {lookingUp && <p className="text-xs text-muted-foreground">Looking up customer…</p>}
            {foundCustomerName && !lookingUp && (
              <p className="text-xs text-green-600 font-medium">✓ Existing customer: {foundCustomerName}</p>
            )}
          </div>

          {/* New / Repeat */}
          <div className="space-y-1">
            <Label>New / Repeat</Label>
            <Controller name="is_new_customer" control={control} render={({ field }) => (
              <Select
                value={field.value === undefined ? '' : field.value ? 'new' : 'repeat'}
                onValueChange={v => { field.onChange(v === 'new'); setNewRepeatAutoFilled(false) }}
              >
                <SelectTrigger><SelectValue placeholder="— Not set —" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="new">New</SelectItem>
                  <SelectItem value="repeat">Repeat</SelectItem>
                </SelectContent>
              </Select>
            )} />
            {newRepeatAutoFilled && (
              <p className="text-xs text-muted-foreground">Auto-detected from order history · edit if needed</p>
            )}
          </div>

          <Separator />

          {/* ── Section 2: Order ──────────────────────────────────────── */}
          <SectionLabel>Order</SectionLabel>

          {/* Date + Channel */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label>Date</Label>
              <Input type="date" {...register('order_date')} />
            </div>
            <div className="space-y-1">
              <Label><Req>Channel</Req></Label>
              <Controller name="channel" control={control} render={({ field }) => (
                <Select value={field.value ?? ''} onValueChange={field.onChange}>
                  <SelectTrigger><SelectValue placeholder="Select channel" /></SelectTrigger>
                  <SelectContent>
                    {CHANNELS.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                  </SelectContent>
                </Select>
              )} />
              {errors.channel && <p className="text-xs text-destructive">{errors.channel.message}</p>}
            </div>
          </div>

          {/* Package */}
          <div className="space-y-1">
            <Label><Req>Package</Req></Label>
            <Select
              value={selectedPackageId ?? 'none'}
              onValueChange={handlePackageSelect}
              disabled={!selectedProjectId}
            >
              <SelectTrigger>
                <SelectValue placeholder={selectedProjectId ? 'Select package' : 'Pick brand first'} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">— None / Enter manually —</SelectItem>
                {projectPackages.map(p => (
                  <SelectItem key={p.id} value={p.id}>{packageLabel(p)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            {!selectedPackageId && (
              <Input
                placeholder="Product / package name"
                {...register('product_name')}
                className="mt-1.5"
              />
            )}
            {errors.product_name && <p className="text-xs text-destructive">{errors.product_name.message}</p>}
          </div>

          {/* Total Price */}
          <div className="space-y-1">
            <Label>Total Price (RM)</Label>
            <Input type="number" step="0.01" placeholder="0.00" {...register('total_price')} />
            {priceAutoFilled && <p className="text-xs text-muted-foreground">Auto-filled from package · edit if needed</p>}
            {errors.total_price && <p className="text-xs text-destructive">{errors.total_price.message}</p>}
          </div>

          <Separator />

          {/* ── Section 3: Additional ─────────────────────────────────── */}
          <SectionLabel>Additional</SectionLabel>

          {/* Remark */}
          <div className="space-y-1">
            <Label>Remark</Label>
            <textarea
              {...register('purchase_reason')}
              rows={2}
              placeholder="Optional remark…"
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm resize-none focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" onClick={handleClose}>Cancel</Button>
            <Button type="submit" disabled={loading}>{loading ? 'Saving…' : 'Submit'}</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
