'use client'

import { useState, useRef } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useQueryClient } from '@tanstack/react-query'
import { orderSchema, type OrderFormData } from '@/lib/validations'
import {
  fetchCustomerByPhone, upsertCustomer, createOrder, generateOrderId,
} from '@/app/actions/data'
import { getCustomerByPhone } from '@/app/actions/customers'
import { createClient } from '@/lib/supabase/client'
import { useProjects, type Package } from '@/lib/hooks/useProjects'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Separator } from '@/components/ui/separator'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import { BRAND_COLORS } from '@/lib/constants'

const AUTO_ID_PROJECTS = ['DD', 'Juji', 'NE', 'FIOR', 'KHH']

const CHANNELS = [
  'FB', 'WhatsApp', 'Shopee', 'FB ENG', 'Lazada', 'Staff', 'WhatsApp ENG', 'Shopee SG',
] as const

const ALLOWED_TYPES = ['image/jpeg', 'image/png', 'image/webp']
const MAX_SIZE = 5 * 1024 * 1024

interface Props { open: boolean; onClose: () => void }

function Req({ children }: { children: React.ReactNode }) {
  return <span>{children} <span className="text-red-500">*</span></span>
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide">{children}</p>
}

interface ReceiptSlot {
  url: string | null
  filePath: string | null
  uploading: boolean
  error: string
}

function emptySlot(): ReceiptSlot {
  return { url: null, filePath: null, uploading: false, error: '' }
}

export default function AddOrderModal({ open, onClose }: Props) {
  const queryClient = useQueryClient()
  const [loading, setLoading] = useState(false)
  const [lookingUp, setLookingUp] = useState(false)
  const [foundCustomerId, setFoundCustomerId] = useState<string | null>(null)
  const [foundCustomerName, setFoundCustomerName] = useState<string | null>(null)
  const [autoFilled, setAutoFilled] = useState<Set<string>>(new Set())
  const [generatingId, setGeneratingId] = useState(false)
  const [autoGeneratedId, setAutoGeneratedId] = useState<boolean>(false)
  const [priceAutoFilled, setPriceAutoFilled] = useState(false)

  const [receipt1, setReceipt1] = useState<ReceiptSlot>(emptySlot())
  const [receipt2, setReceipt2] = useState<ReceiptSlot>(emptySlot())
  const fileRef1 = useRef<HTMLInputElement>(null)
  const fileRef2 = useRef<HTMLInputElement>(null)

  const phoneDebounceRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const today = new Date().toISOString().split('T')[0]

  const { register, handleSubmit, setValue, watch, reset, control, formState: { errors } } = useForm<OrderFormData>({
    resolver: zodResolver(orderSchema),
    defaultValues: { status: 'pending', order_date: today, package_id: null },
  })

  const selectedProjectId = watch('project_id')

  const { projects } = useProjects()
  const projectPackages: Package[] = projects.find(p => p.id === selectedProjectId)?.packages ?? []

  const selectedProject = projects.find(p => p.id === selectedProjectId)
  const brandColor = selectedProject ? BRAND_COLORS[selectedProject.name] : null

  async function lookupPhone() {
    let phone = watch('customer_phone') ?? ''
    if (/^0\d/.test(phone)) {
      phone = '6' + phone
      setValue('customer_phone', phone)
    }
    if (!phone || phone.length < 8) return
    setLookingUp(true)
    const customer = await fetchCustomerByPhone(phone)
    if (customer) {
      setValue('customer_name', customer.name)
      setFoundCustomerId(customer.id)
      setFoundCustomerName(customer.name)
      setAutoFilled(new Set(['customer_name']))
    } else {
      setFoundCustomerId(null)
      setFoundCustomerName(null)
      setAutoFilled(new Set())
    }
    setLookingUp(false)
  }

  async function handleProjectChange(projectId: string) {
    setValue('product_name', '')
    setValue('package_name', '')
    setValue('package_id', null)

    const proj = projects.find(p => p.id === projectId)
    if (proj && AUTO_ID_PROJECTS.includes(proj.name)) {
      setGeneratingId(true)
      setAutoGeneratedId(false)
      try {
        const newId = await generateOrderId(projectId)
        setValue('tracking_number', newId)
        setAutoGeneratedId(true)
      } catch (err) {
        console.error('Failed to generate order ID:', err)
        setValue('tracking_number', null)
        setAutoGeneratedId(false)
      } finally {
        setGeneratingId(false)
      }
    } else {
      setValue('tracking_number', null)
      setAutoGeneratedId(false)
    }
  }

  async function uploadReceiptFile(
    file: File,
    slot: ReceiptSlot,
    setSlot: React.Dispatch<React.SetStateAction<ReceiptSlot>>,
  ) {
    if (!ALLOWED_TYPES.includes(file.type)) {
      setSlot(s => ({ ...s, error: 'Only JPG, PNG, WEBP allowed' }))
      return
    }
    if (file.size > MAX_SIZE) {
      setSlot(s => ({ ...s, error: 'File must be under 5MB' }))
      return
    }

    setSlot(s => ({ ...s, uploading: true, error: '' }))

    // Remove previous upload if replaced
    if (slot.filePath) {
      createClient().storage.from('receipts').remove([slot.filePath]).catch(() => {})
    }

    const timestamp = Date.now()
    const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_')
    const path = `orders/${timestamp}_${safeName}`

    try {
      const supabase = createClient()
      const { error } = await supabase.storage.from('receipts').upload(path, file, {
        contentType: file.type,
        upsert: true,
      })
      if (error) throw error
      const { data: { publicUrl } } = supabase.storage.from('receipts').getPublicUrl(path)
      setSlot({ url: publicUrl, filePath: path, uploading: false, error: '' })
    } catch (err: any) {
      setSlot(s => ({ ...s, uploading: false, error: err?.message ?? 'Upload failed' }))
    }
  }

  async function onSubmit(data: OrderFormData) {
    setLoading(true)
    try {
      let customerId = foundCustomerId
      if (!customerId && data.customer_phone) {
        customerId = await upsertCustomer(data.customer_name ?? '', data.customer_phone)
      }
      await createOrder({
        customer_id: customerId,
        project_id: data.project_id,
        package_id: data.package_id ?? null,
        product_name: data.product_name,
        package_name: data.package_name || null,
        total_price: data.total_price,
        status: data.status,
        order_date: data.order_date,
        fb_name: null,
        channel: data.channel,
        purchase_reason: null,
        remark: data.remark || null,
        payment_method_1: null,
        payment_method_2: null,
        is_new_customer: true,
        tracking_number: data.tracking_number ?? null,
        state: null,
        address: null,
        receipt_url_1: receipt1.url,
        receipt_url_2: receipt2.url,
      })
      toast.success('Order created')
      queryClient.invalidateQueries({ queryKey: ['orders'] })
      queryClient.invalidateQueries({ queryKey: ['dashboard'] })
      // Clear file paths so handleClose doesn't delete successfully saved receipts
      setReceipt1(emptySlot())
      setReceipt2(emptySlot())
      handleClose()
    } catch (e: any) {
      toast.error(e.message ?? 'Failed to create order')
    } finally {
      setLoading(false)
    }
  }

  function handleClose() {
    // Clean up any uploaded-but-unsaved receipt files
    if (receipt1.filePath) createClient().storage.from('receipts').remove([receipt1.filePath]).catch(() => {})
    if (receipt2.filePath) createClient().storage.from('receipts').remove([receipt2.filePath]).catch(() => {})
    reset({ status: 'pending', order_date: today, package_id: null, tracking_number: null })
    setFoundCustomerId(null)
    setFoundCustomerName(null)
    setAutoFilled(new Set())
    setAutoGeneratedId(false)
    setPriceAutoFilled(false)
    setReceipt1(emptySlot())
    setReceipt2(emptySlot())
    onClose()
  }

  function handlePackageSelect(packageId: string) {
    if (packageId === 'none') {
      setValue('product_name', '')
      setValue('package_name', '')
      setValue('package_id', null)
      setValue('total_price', '' as any)
      setPriceAutoFilled(false)
      return
    }
    const pkg = projectPackages.find(p => p.id === packageId)
    if (!pkg) return
    setValue('product_name', pkg.name)
    setValue('package_name', pkg.name)
    setValue('package_id', pkg.id)
    if (pkg.price > 0) {
      setValue('total_price', pkg.price)
      setPriceAutoFilled(true)
    } else {
      setValue('total_price', '' as any)
      setPriceAutoFilled(false)
    }
  }

  function packageLabel(pkg: Package): string {
    const parts: string[] = []
    if (pkg.code) parts.push(`[${pkg.code}]`)
    parts.push(pkg.name)
    parts.push(`— RM ${pkg.price.toFixed(2)}`)
    return parts.join(' ')
  }

  const isAuto = (f: string) => autoFilled.has(f)
  const selectedPackageId = watch('package_id')

  function ReceiptUpload({
    label,
    slot,
    setSlot,
    fileRef,
  }: {
    label: string
    slot: ReceiptSlot
    setSlot: React.Dispatch<React.SetStateAction<ReceiptSlot>>
    fileRef: React.RefObject<HTMLInputElement>
  }) {
    function handleRemove() {
      if (slot.filePath) createClient().storage.from('receipts').remove([slot.filePath]).catch(() => {})
      setSlot(emptySlot())
      if (fileRef.current) fileRef.current.value = ''
    }

    return (
      <div className="space-y-1">
        <Label>{label}</Label>
        {slot.url ? (
          <div className="space-y-2">
            <img src={slot.url} alt={label} className="h-20 rounded border object-cover" />
            <div className="flex gap-2">
              <label className={cn('cursor-pointer text-xs text-muted-foreground underline', slot.uploading && 'opacity-50 pointer-events-none')}>
                Replace
                <input
                  ref={fileRef}
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  className="sr-only"
                  onChange={e => {
                    const file = e.target.files?.[0]
                    if (fileRef.current) fileRef.current.value = ''
                    if (file) uploadReceiptFile(file, slot, setSlot)
                  }}
                />
              </label>
              <button type="button" onClick={handleRemove} className="text-xs text-destructive underline">Remove</button>
            </div>
          </div>
        ) : (
          <label className={cn(
            'flex flex-col items-center justify-center gap-1 border border-dashed rounded-md p-3 cursor-pointer',
            'text-xs text-muted-foreground hover:border-primary/50 transition-colors',
            slot.uploading && 'opacity-60 pointer-events-none',
          )}>
            {slot.uploading ? (
              <span className="flex items-center gap-1.5">
                <svg className="animate-spin h-3 w-3" viewBox="0 0 24 24" fill="none">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
                </svg>
                Uploading…
              </span>
            ) : (
              <>
                <span>Click to upload</span>
                <span className="text-[10px]">JPG, PNG, WEBP · max 5MB</span>
              </>
            )}
            <input
              ref={fileRef}
              type="file"
              accept="image/jpeg,image/png,image/webp"
              className="sr-only"
              onChange={e => {
                const file = e.target.files?.[0]
                if (fileRef.current) fileRef.current.value = ''
                if (file) uploadReceiptFile(file, slot, setSlot)
              }}
            />
          </label>
        )}
        {slot.error && <p className="text-xs text-destructive">{slot.error}</p>}
      </div>
    )
  }

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader><DialogTitle>Add Order</DialogTitle></DialogHeader>

        {/* Brand selector + color pill */}
        <div className="space-y-1 -mt-1">
          <Controller name="project_id" control={control} render={({ field }) => (
            <Select value={field.value ?? ''} onValueChange={v => { field.onChange(v); handleProjectChange(v) }}>
              <SelectTrigger className={cn(brandColor && cn(brandColor.bg, brandColor.text, brandColor.border))}>
                <SelectValue placeholder="Select brand *" />
              </SelectTrigger>
              <SelectContent>
                {projects.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
              </SelectContent>
            </Select>
          )} />
          {errors.project_id && <p className="text-xs text-destructive">{errors.project_id.message}</p>}
          {generatingId && <p className="text-xs text-muted-foreground">Generating order ID…</p>}
        </div>

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-3">

          {/* ── Section 1: Customer ───────────────────────────────────── */}
          <SectionLabel>Customer</SectionLabel>

          {/* Name */}
          <div className="space-y-1">
            <Label>名字</Label>
            <Input
              placeholder="Full name"
              {...register('customer_name')}
              className={cn(isAuto('customer_name') && 'text-red-600 border-red-200')}
            />
            {isAuto('customer_name') && <p className="text-xs text-red-500">Auto-filled from phone lookup</p>}
          </div>

          {/* Phone */}
          <div className="space-y-1">
            <Label>Phone No</Label>
            <Input
              placeholder="601xxxxxxxx"
              {...register('customer_phone', {
                onChange: e => {
                  if (!e.target.value.trim()) {
                    setFoundCustomerId(null)
                    setFoundCustomerName(null)
                    setAutoFilled(new Set())
                  }
                  if (phoneDebounceRef.current) clearTimeout(phoneDebounceRef.current)
                  phoneDebounceRef.current = setTimeout(lookupPhone, 600)
                },
              })}
              onBlur={lookupPhone}
            />
            {lookingUp && <p className="text-xs text-muted-foreground">Looking up customer…</p>}
            {foundCustomerName && !lookingUp && (
              <p className="text-xs text-green-600 font-medium">✓ Existing customer: {foundCustomerName}</p>
            )}
          </div>

          <Separator />

          {/* ── Section 2: Order ──────────────────────────────────────── */}
          <SectionLabel>Order</SectionLabel>

          {/* Date + Channel */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <Label>Date</Label>
              <Input type="date" {...register('order_date')} />
            </div>
            <div className="space-y-1">
              <Label><Req>Channel</Req></Label>
              <Controller name="channel" control={control} render={({ field }) => (
                <Select value={field.value ?? ''} onValueChange={field.onChange}>
                  <SelectTrigger><SelectValue placeholder="Select channel" /></SelectTrigger>
                  <SelectContent>
                    {CHANNELS.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                  </SelectContent>
                </Select>
              )} />
              {errors.channel && <p className="text-xs text-destructive">{errors.channel.message}</p>}
            </div>
          </div>

          {/* Package */}
          <div className="space-y-1">
            <Label><Req>Package</Req></Label>
            <Select
              value={selectedPackageId ?? 'none'}
              onValueChange={handlePackageSelect}
              disabled={!selectedProjectId}
            >
              <SelectTrigger>
                <SelectValue placeholder={selectedProjectId ? 'Select package' : 'Pick brand first'} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">— None / Enter manually —</SelectItem>
                {projectPackages.map(p => (
                  <SelectItem key={p.id} value={p.id}>{packageLabel(p)}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            {!selectedPackageId && (
              <Input
                placeholder="Product / package name"
                {...register('product_name')}
                className="mt-1.5"
              />
            )}
            {errors.product_name && <p className="text-xs text-destructive">{errors.product_name.message}</p>}
          </div>

          {/* Total Price */}
          <div className="space-y-1">
            <Label>Total Price (RM)</Label>
            <Input type="number" step="0.01" placeholder="0.00" {...register('total_price')} />
            {priceAutoFilled && <p className="text-xs text-muted-foreground">Auto-filled from package · edit if needed</p>}
            {errors.total_price && <p className="text-xs text-destructive">{errors.total_price.message}</p>}
          </div>

          {/* Notes / Remark */}
          <div className="space-y-1">
            <Label>Notes / Remark 备注</Label>
            <textarea
              {...register('remark')}
              rows={2}
              placeholder="Optional notes…"
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-sm resize-none focus:outline-none focus:ring-1 focus:ring-ring"
            />
          </div>

          <Separator />

          {/* ── Section 3: Receipts ───────────────────────────────────── */}
          <SectionLabel>Receipts</SectionLabel>

          <div className="grid grid-cols-2 gap-3">
            <ReceiptUpload label="Receipt 1" slot={receipt1} setSlot={setReceipt1} fileRef={fileRef1} />
            <ReceiptUpload label="Receipt 2" slot={receipt2} setSlot={setReceipt2} fileRef={fileRef2} />
          </div>

          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" onClick={handleClose}>Cancel</Button>
            <Button type="submit" disabled={loading || receipt1.uploading || receipt2.uploading}>
              {loading ? 'Saving…' : 'Submit'}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
